### ISSUE TITLE
Add a kickass @mitchett original soundtrack!

### ISSUE THREAD

**Issue by ramondelafuente** [ramondelafuente/moonshot#16]

**Comment by michielpapenhove** [comment]
I've picked a few tracks that I think would fit the game nicely. Went for an EDM direction but if you think we should look into another direction, do let me know.

https://soundcloud.com/michett/laserbeam
https://soundcloud.com/michett/bounce
https://soundcloud.com/michett/snap
https://soundcloud.com/michett/elevator
https://soundcloud.com/michett/drop
https://soundcloud.com/michett/howl
https://soundcloud.com/michett/sprite
https://soundcloud.com/michett/ghost
https://soundcloud.com/michett/ninety
https://soundcloud.com/michett/sea-drone
